doc/urls.py
from django.urls import path
from .views import create_doctor_view,doctor_list_view,\
    specialization_view,patients_list_view,\
    edit_specialization_view,\
    delete_specialization_view,\
     doctors_view,\
     patience_book_appointment,\
     patient_pick_cat,\
    pentience_appointment_list_view,\
    doctor_view_patirnt_appointment,\
    doctor_view_app_id,\
     rep_view,\
     doctor_view_app_declined,\
    view_accepted_appointment_list,\
     doctors_list_declined,\
      doctors_manage_patient,\
     delete_doctors_manage_patient,\
     admin_declined_appointment_list_view,\
    create_pham_view,\
    displays_pharmacy_to_admin,\
     pentience_send_view,\
    pentience_view_prescription,\
     pentience_send_prescription_view,\
    pentience_send_prescription_list,\
     pharmacy_view_patient_prescription,\
     pharmacy_view_id_patient,\
     declined_drug_view,\
     phar_view_approved_drug,\
      phar_view_declined_drug,\
     phar_display_pre_drug,\
     prescription_update_pa,\
     prescription_declined_update_pa,\
     prescription_update_pa_id,\
     doctor_change_password_view,\
     pharmacy_change_password,\
     super_admin_delete_view,\
     admin_delete_studdent_view,\
     admin_view_patient,\
     displays_pharmacy_to_admin_edit,\
     pharmac_pro_pic_view,\
     doctor_pro_pic_view,\
     patient_pro_pic_view,\
     admin_view_appointment_ap,\
     admin_view_declined_appointment_ap,\
      admin_view_accepted_prescription_ap,\
     admin_view_declined_prescription_ap,\
     admin_view_pending_appointment_ap,\
     chat_view,\
     reload_chat,\
     dr_chat,\
     dr_send_chat,\
     reload_chat_dr



app_name = 'create'
urlpatterns = [
    path('create_doctor/', create_doctor_view, name='create_doctor'),
    path('doctors-list/', doctor_list_view, name='doctors-list'),
    path('specialization_view/', specialization_view, name='specialization_view'),
    path('patients-list-view/', patients_list_view, name='patients-list-view'),
    path('edit-spe/<id>/', edit_specialization_view, name="edit-spe"),
    path('delete-specialization/<id>/', delete_specialization_view, name="delete-specialization"),
    path('view-doctor/<id>/', doctors_view, name="view-doctor"),
    path('patience-book-appointment/<id>/', patience_book_appointment, name="patience-book-appointment"),
    path('patient-pick-cat/', patient_pick_cat, name="patient-pick-cat"),
    path('pentience-appointment-list-view/', pentience_appointment_list_view, name="pentience-appointment-list-view"),
    path('doctor-view-patirnt-appointment/<id>/', doctor_view_patirnt_appointment, name="doctor-view-patirnt-appointment"),
    path('doctor-view-app-id/<id>/', doctor_view_app_id, name="doctor-view-app-id"),
    path('rep_view/<id>/', rep_view, name="rep_view"),
    path('doctor-view-app-declined/<id>/', doctor_view_app_declined, name="doctor-view-app-declined"),
    path('view_accepted_appointment_list/',view_accepted_appointment_list, name="view_accepted_appointment_list"),
    path('doctors-list-declined/', doctors_list_declined, name="doctors-list-declined"),
    path('doctors-manage-patient/<id>/', doctors_manage_patient, name="doctors-manage-patient"),
    path('delete-doctors-manage-patient/<id>/',delete_doctors_manage_patient, name="delete-doctors-manage-patient"),
    path('admin-declined-appointment-list_view', admin_declined_appointment_list_view, name="admin-declined-appointment-list-view"),
    path('create-pham-view/',create_pham_view, name="create-pham-view"),
    path('displays-pharmacy-to-admin/',displays_pharmacy_to_admin, name="displays-pharmacy-to-admin"),
    path('pentience-send-view/',pentience_send_view, name="pentience-send-view"),
    path('pentience-view-prescription/<id>/',pentience_view_prescription, name="pentience-view-prescription"),
    path('pentience-send-prescription_view/<id>/',pentience_send_prescription_view, name="pentience-send-prescription-view"),
    path('pentience-send-prescription-list/<id>/',pentience_send_prescription_list, name="pentience-send-prescription-list"),
    path('pharmacy-view-patient-prescription/', pharmacy_view_patient_prescription,name="pharmacy-view-patient-prescription"),
    path('pharmacy-view-id-patient/<uuid:u_id>/', pharmacy_view_id_patient,name="pharmacy-view-id-patient"),



    path('declined-drug-view/<uuid:u_id>/',declined_drug_view, name="declined-drug-view"),

    path('phar-view-approved-drug/',phar_view_approved_drug, name="phar-view-approved-drug"),


    path('phar-view-declined-drug/',phar_view_declined_drug, name="phar-view-declined-drug"),
    path('phar-display-pre-drug/<id>/',phar_display_pre_drug, name="phar-display-pre-drug"),
    path('prescription-update-pa/', prescription_update_pa, name="prescription-update-pa"),
    path('prescription-declined-update-pa/', prescription_declined_update_pa, name="prescription-declined-update-pa"),
    path('prescription-update-pa-id/<id>', prescription_update_pa_id, name="prescription-update-pa-id"),


    path('doctor-change-password-view/', doctor_change_password_view, name="doctor-change-password-view"),
    path('pharmacy-change-password/', pharmacy_change_password, name="pharmacy-change-password"),
    path('super-admin-delete-view/<id>', super_admin_delete_view, name="super-admin-delete-view"),
    path('admin-delete-studdent-view/<id>', admin_delete_studdent_view, name="admin-delete-studdent-view"),

    path('admin-view-patient/<id>', admin_view_patient, name="admin-view-patient"),
    path('displays-pharmacy-to-admin-edit/<id>/', displays_pharmacy_to_admin_edit, name="displays-pharmacy-to-admin-edit"),
    path('pharmac-pro-pic-view', pharmac_pro_pic_view, name="pharmac-pro-pic-view"),
    path('doctor-pro-pic-view', doctor_pro_pic_view, name="doctor-pro-pic-view"),
    path('patient-pro-pic-view', patient_pro_pic_view, name="patient-pro-pic-view"),


    path('admin_view_appointment_ap', admin_view_appointment_ap, name="admin_view_appointment_ap"),
    path('admin_view_declined_appointment_ap', admin_view_declined_appointment_ap, name="admin_view_declined_appointment_ap"),

    path('admin_view_accepted_prescription_ap', admin_view_accepted_prescription_ap, name="admin_view_accepted_prescription_ap"),
    path('admin_view_declined_prescription_ap', admin_view_declined_prescription_ap, name="admin_view_declined_prescription_ap"),

    path('admin_view_pending_appointment_ap', admin_view_pending_appointment_ap, name="admin_view_pending_appointment_ap"),


    #"""this is the chat Url"""
    path('chat-view', chat_view,name="chat_view"),

    # """this is the chat Url"""
    path('reload-chat/<id>/',reload_chat,name="reload_chat"),
    #Dr chat url

    path('dr-chat/',dr_chat, name="dr_chat"),
    path('dr-send-chat',dr_send_chat, name="dr_send_chat"),

    path('reload-chat-dr/<id>/', reload_chat_dr,name="reload_chat_dr"),
]

doctors/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from user.views import home_page_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.urls', namespace="log")),
    path('',include('doc.urls', namespace="create")),
    path('', home_page_view, name='home_page'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import Doc_login_view,success_view,Doc_logout_view,\
    user_signup_view,patients_login_view,patients_success_view\
    ,doc_success_view,doctormain_login_view,pharmacy_login_view,\
    pharmacy_home_view,home_qual_view,doctor_logout_view,patient_logout_view,pharm_logout_view
app_name="log"
urlpatterns = [
    path('login/', Doc_login_view, name='login'),
    path('success/', success_view, name='success'),
    path('logout/', Doc_logout_view, name='logout'),
    path('user-signup/', user_signup_view,name='user-signup'),
    path('patients_login/',patients_login_view, name='patients_login'),
    path('patients_success/', patients_success_view, name='patients_success'),
    path('doctor-main-success/', doc_success_view, name='doctor-main-success'),
    path('doctormain-login-view/', doctormain_login_view, name='doctormain-login-view'),
    path('pharmacy-login-view/', pharmacy_login_view, name='pharmacy-login-view'),
    path('pharmacy-home-view/', pharmacy_home_view, name='pharmacy-home-view'),
    path('home-qual-view/', home_qual_view, name='home-qual-view'),
    path('doctor-logout-view/', doctor_logout_view, name='doctor-logout-view'),
    path('patient-logout-view/', patient_logout_view, name='patient-logout-view'),
    path('pharm-logout-view/', pharm_logout_view, name='pharm-logout-view'),
]

templates/admin-pharm-list.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SB Admin 2 - Dashboard</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'bootstrap/vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
<link href="{% static 'bootstrap/fonts/css/font-awesome.min.css'%}" rel="stylesheet">
  <!-- Custom styles for this template-->
  <link href="{% static 'bootstrap/css/sb-admin-2.min.css'%}" rel="stylesheet">
<link href="{% static 'bootstrap/css/fontawesome-all.min.css' %}" rel="stylesheet">


</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-user"></i>
        </div>
        <div class="sidebar-brand-text mx-3">{{user}} <sup></sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="index.html">
          <i class="fa fa-user"></i>
          <span style="color:Black;">Admin</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Interface
      </div>

      <!-- Nav Item - Pages Collapse Menu -->


      <!-- Nav Item - Utilities Collapse Menu -->

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Addons
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <!-- Nav Item - Charts -->
      <li class="nav-item">
        <a class="nav-link" href="{%url 'log:success'%}">
          <i class="fa fa-home"></i>
          <span>Home</span></a>
      </li>


      <!-- Nav Item - Charts -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'create:create_doctor' %}">
          <i class="fas fa-stethoscope"></i>
          <span>Add Doctors</span></a>
      </li>

      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'create:doctors-list' %}">
          <i class="fas fa-user-md"></i>
          <span>List Of Doctors ({{doc}})</span></a>
      </li>

     <li class="nav-item">
        <a class="nav-link" href="{% url 'create:specialization_view' %}">
          <i class="far fa-list-alt"></i>&nbsp;
          <span>Add Specialization</span></a>
      </li>

           <li class="nav-item">
        <a class="nav-link" href="{% url 'create:admin_view_pending_appointment_ap' %}">
          <i class="fa fa-clock-o"></i>&nbsp;
          <span>pending Appointments({{book_pending_c}})</span></a>
      </li>

           <li class="nav-item">
        <a class="nav-link" href="{%url 'create:patients-list-view' %}">
          <i class="fas fa-user"></i>&nbsp;
          <span>Patients List ({{pat_count}})</span></a>
      </li>


           <li class="nav-item">
        <a class="nav-link" href="{%url 'create:displays-pharmacy-to-admin' %}">
          <i class="fa fa-remove"></i>&nbsp;
          <span>Declined List Detail ({{book_declined_c}})</span></a>
      </li>

           <li class="nav-item">
        <a class="nav-link" href="{%url 'create:create-pham-view' %}">
          <i class="fas fa-microscope"></i>&nbsp;
          <span>Add Pharmacy</span></a>
      </li>
          <li class="nav-item">
        <a class="nav-link" href="{% url 'create:specialization_view' %}">
          <i class="fas fa-user-nurse"></i>&nbsp;
          <span>Pharmacy List ({{ph1}})</span></a>
      </li>
           <li class="nav-item">
        <a class="nav-link" href="{%url 'create:admin_view_appointment_ap' %}">
          <i class="fas fa-diagnoses"></i>&nbsp;
          <span>Acc booked App({{book_c}})</span></a>
      </li>

           <li class="nav-item">
        <a class="nav-link" href="{%url 'create:admin_view_declined_appointment_ap' %}">
          <i class="fa fa-remove"></i>&nbsp;
          <span>De booked App({{book_declined_c}})</span></a>
      </li>

           <li class="nav-item">
        <a class="nav-link" href="{%url 'create:admin_view_accepted_prescription_ap' %}">
          <i class="fas fa-diagnoses"></i>&nbsp;
          <span>Approved Prescriptions({{sed_w}})</span></a>
      </li>

           <li class="nav-item">
        <a class="nav-link" href="{%url 'create:admin_view_accepted_prescription_ap' %}">
          <i class="fa fa-remove"></i>&nbsp;
          <span>Declined Prescriptions ({{sed_i}}) </span></a>
      </li>




       <li class="nav-item">
        <a class="nav-link" href="{%url 'log:logout'%}">
          <i class="fas fa-sign-out-alt"></i>&nbsp;
          <span>Logout</span></a>
      </li>



      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            <!-- Nav Item - Alerts -->


            <!-- Nav Item - Messages -->

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small"><strong>{{user}}</strong></span>
                <!--<img class="img-profile rounded-circle" src="{{user.image.url}}">-->
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- Begin Page Content -->
        <div class="container-fluid">
        <div class="mt-5">
        {%if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}}" role="alert">
             {{message}}
          </div>
        {% endfor %}
        {% endif %}
        </div>
          <!-- Page Heading -->
          <!-- Content Row -->
          <div class="row">

            <!-- Earnings (Monthly) Card Example -->

            <div class="col-md-12">
     <table class="table">

      <thead>
           <th></th>
           <th>Id</th>
           <th>Pharmacy Name</th>

           <th>Email</th>
          <th>password</th>
          <th>Edit</th>





    </thead>
    <tbody>

    <tr>
   {%for j in ph%}
    <td><input type="checkbox" class="checkthis" /></td>
    <td>{{j.id}}</td>
      <td>{{j.First_name}} {{j.Other_name}}</td>
        <td>{{j.email}}</td>
        <td>{{j.password}}</td>
      <td><a href="{%url 'create:displays-pharmacy-to-admin-edit' j.id%}"><button class="btn btn-info">Edit</button></a></td>
        {%endfor%}
    </tr>


    </tbody>

</table>



            </div>



          </div>


  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'bootstrap/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'bootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'bootstrap/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'bootstrap/js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="vendor/chart.js/Chart.min.js"></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'bootstrap/js/demo/chart-area-demo.js' %}"></script>
  <script src="{% static 'bootstrap/js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>

templates/doctor-login.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SB Admin 2 - Dashboard</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'bootstrap/vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'bootstrap/css/sb-admin-2.min.css'%}" rel="stylesheet">

</head>




<body class="bg-gradient-primary">
    <div class="mt-5">
   {%if messages %}
   {% for message in messages %}
      <div class="alert alert-{{message.tags}}" role="alert">
         {{message}}
      </div>
    {% endfor %}
    {% endif %}
  </div>
  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div  style="padding:15px;">
              <img src="{% static 'image/pic.jpg'%}" alt="user">
              </div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                  </div>
                  <form class="user" method="POST" action=".">
                      {%csrf_token%}
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user"  aria-describedby="emailHelp"  name="email" placeholder="Email">
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" name="passe" placeholder="Password">
                    </div>
                      <button class="btn btn-primary btn-user btn-block">Login</button>
                    <hr>
                  </form>
                  <div class="text-center">
                    <a class="small" href="forgot-password.html">Forgot Password?</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="register.html">Create an Account!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>
  <script src="{% static 'bootstrap/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'bootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'bootstrap/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'bootstrap/js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="vendor/chart.js/Chart.min.js"></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'bootstrap/js/demo/chart-area-demo.js' %}"></script>
  <script src="{% static 'bootstrap/js/demo/chart-pie-demo.js' %}"></script>
</body>
</html>